require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'HackerNews' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  target 'HackerNewsTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)

    # Modern clang reports Yoga's `bool | bool` as -Wbitwise-instead-of-logical and
    # (Xcode 26.6+) its `operator"" _pt` spelling as -Wdeprecated-literal-operator,
    # which Yoga.podspec's -Werror makes fatal. Keep them warnings (no codegen change).
    installer.pods_project.targets.each do |target|
      next unless target.name == 'Yoga'
      target.build_configurations.each do |config|
        config.build_settings['OTHER_CFLAGS'] = '$(inherited) -Wno-error=bitwise-instead-of-logical -Wno-error=deprecated-literal-operator'
      end
    end

    # Xcode 14+ code-signs resource bundle targets. CocoaPods >= 1.12 disables that
    # ("Xcode 14.x throws an error about code signing on resource bundles"), but this
    # repository pins CocoaPods 1.11.3, so apply the same setting here.
    installer.pods_project.targets.each do |target|
      next unless target.respond_to?(:product_type) && target.product_type == 'com.apple.product-type.bundle'
      target.build_configurations.each do |config|
        config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
      end
    end

    # Pods integrated only for Debug (use_flipper!) must not be compiled or linked
    # in Release. CocoaPods still integrates their transitive dependencies into
    # Release, so take the closure: a pod is Debug-only when it is not a direct
    # Release dependency and every pod depending on it is Debug-only.
    aggregates = installer.aggregate_targets
    pod_targets = aggregates.flat_map(&:pod_targets).uniq
    release_pods = aggregates.flat_map { |t| t.pod_targets_for_build_configuration('Release') }.map(&:name).uniq
    debug_only_pods = pod_targets.map(&:name) - release_pods
    direct_release_pods = aggregates.flat_map do |t|
      t.target_definition.dependencies.map(&:root_name).select { |name| t.target_definition.pod_whitelisted_for_configuration?(name, 'Release') }
    end
    dependents = Hash.new { |hash, key| hash[key] = [] }
    pod_targets.each { |pt| pt.dependent_targets.each { |dep| dependents[dep.name] << pt.name } }
    loop do
      added = (release_pods - debug_only_pods - direct_release_pods).select do |name|
        dependents[name].any? && (dependents[name] - debug_only_pods).empty?
      end
      break if added.empty?
      debug_only_pods += added
    end
    Pod::UI.puts "Debug-only pods excluded from Release: #{debug_only_pods.sort.join(', ')}"

    installer.pods_project.targets.each do |target|
      next unless debug_only_pods.include?(target.name)
      target.build_configurations.each do |config|
        config.build_settings['EXCLUDED_SOURCE_FILE_NAMES'] = '*' if config.name == 'Release'
      end
    end
    aggregates.each do |target|
      path = target.xcconfig_path('Release')
      xcconfig = File.read(path)
      debug_only_pods.each do |name|
        xcconfig = xcconfig.gsub(" -l\"#{name}\"", '')
        xcconfig = xcconfig.gsub(" -fmodule-map-file=\"${PODS_CONFIGURATION_BUILD_DIR}/#{name}/#{name}.modulemap\"", '')
      end
      File.write(path, xcconfig)
    end
  end
end